/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.1 and the Signal Processing Toolbox 7.3.
 * Generated on: 14-Oct-2021 10:00:36
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 5
 * Denominator Length  : 5
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2016b\extern\include\tmwtypes.h 
 */
// const int NL = 5;
#define NL_HP 5
const real64_T NUM_HP[5] = {
		0.9967216337146,   -3.986886534858,    5.980329802288,   -3.986886534858,
		     0.9967216337146
};
//const int DL = 5;
#define DL_HP
const real64_T DEN_HP[5] = {
		1,    -3.99343249906,    5.980319054622,   -3.980340570637,
		     0.9934540151147
};
