########################################################################
#Cátedra: Electrónica Programable
#FIUNER
#2018
#Autor/es:
#JMreta - jmreta@ingenieria.uner.edu.ar
#
#Revisión:
########################################################################

# Ruta del Proyecto
####Ejemplo 1: Hola Mundo
##Por el primero, se debe usar Makefile1
#PROYECTO_ACTIVO = 1_hola_mundo
#NOMBRE_EJECUTABLE = hola_mundo.exe

####Ejemplo 2: Control Mundo
#PROYECTO_ACTIVO = 2_control_mundo
#NOMBRE_EJECUTABLE = control_mundo.exe

####Ejemplo 3: Promedio
#PROYECTO_ACTIVO = 3_promedio_1
#NOMBRE_EJECUTABLE = promedio.exe

#PROYECTO_ACTIVO = 5_menu
#NOMBRE_EJECUTABLE = menu.exe

#PROYECTO_ACTIVO = Ej_c_d_e
#NOMBRE_EJECUTABLE = c_d_e.exe

#PROYECTO_ACTIVO = ejercitacion01
#NOMBRE_EJECUTABLE = ejercitacion01.exe

#PROYECTO_ACTIVO = EJERCICIO_07_PRACTICA_01
#NOMBRE_EJECUTABLE = EJERCICIO_07_PRACTICA_01.exe

#PROYECTO_ACTIVO = EJERCICIO_09_PRACTICA_01
#NOMBRE_EJECUTABLE = EJERCICIO_09_PRACTICA_01.exe

#PROYECTO_ACTIVO = EJERCICIO_12_PRACTICA_01
#NOMBRE_EJECUTABLE = EJERCICIO_12_PRACTICA_01.exe

#PROYECTO_ACTIVO = EJERCICIO_14_PRACTICA_01
#NOMBRE_EJECUTABLE = EJERCICIO_14_PRACTICA_01.exe

#PROYECTO_ACTIVO = EJERCICIO_16_PRACTICA_01
#NOMBRE_EJECUTABLE = EJERCICIO_16_PRACTICA_01.exe

#PROYECTO_ACTIVO = EJERCICIO_17_PRACTICA_01
#NOMBRE_EJECUTABLE = EJERCICIO_17_PRACTICA_01.exe

#PROYECTO_ACTIVO = INTEGRADOR_A_PRACTICA_01
#NOMBRE_EJECUTABLE = INTEGRADOR_A_PRACTICA_01.exe

#PROYECTO_ACTIVO = INTEGRADOR_C_PRACTICA_01
#NOMBRE_EJECUTABLE = INTEGRADOR_C_PRACTICA_01.exe

PROYECTO_ACTIVO = INTEGRADOR_D_PRACTICA_01
NOMBRE_EJECUTABLE = INTEGRADOR_D_PRACTICA_01.exe